on:
  push:
    branches:
    - main

jobs:
  trigger:
    name: Trigger Personal Blog Update
    runs-on: ubuntu-latest
    steps:
    - name: Trigger
      uses: convictional/trigger-workflow-and-wait@v1.6.5
      with:
        owner: ksivamuthu
        repo: personal-blog
        github_token: ${{ secrets.GH_PAT_TOKEN }}
        workflow_file_name: fetch.yml
